arm_controller:
  ros__parameters:
    joints:
      - arm_link1_joint
      - arm_link2_joint
      - arm_link3_joint
      - arm_link4_joint
      - arm_link5_joint
    write_op_modes:
      - arm_link1_joint
      - arm_link2_joint
      - arm_link3_joint
      - arm_link4_joint
      - arm_link5_joint