controller_joint_names: ['', 'arm_link1_joint', 'arm_link2_joint', 'arm_link3_joint', 'arm_link4_joint', 'arm_link5_joint', 'gripper_finger1_joint', 'gripper_finger2_joint', 'gripper_finger3_joint', ]
